"""add creation_time to Measurement

Revision ID: 053cfa130101
Revises: 03ddf61b5b3c
Create Date: 2022-01-11 19:44:59.848230

"""
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy import func

from alembic import op

revision = "053cfa130101"
down_revision = "03ddf61b5b3c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "measurement",
        sa.Column(
            "creation_time", sa.DateTime(), nullable=False, server_default=func.now()
        ),
    )
    op.alter_column("measurement", "creation_time", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("measurement", "creation_time")
    # ### end Alembic commands ###
