"""remove reserved tags

Revision ID: 1d8077da4ad6
Revises: 8a9c14d43b43
Create Date: 2023-11-12 16:53:06.460545

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1d8077da4ad6"
down_revision = "8a9c14d43b43"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "allow_tag_reserved")
    op.drop_column("user", "allow_tag_public")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "allow_tag_public", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "allow_tag_reserved", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
