"""add creation_time to UserTable

Revision ID: 2f6d40d1b807
Revises: 3bfd4e486e3f
Create Date: 2022-01-23 17:31:16.118882

"""
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy import func

from alembic import op

revision = "2f6d40d1b807"
down_revision = "3bfd4e486e3f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "creation_time", sa.DateTime(), server_default=func.now(), nullable=False
        ),
    )
    op.alter_column("user", "creation_time", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "creation_time")
    # ### end Alembic commands ###
