"""Add SQLModel

Revision ID: 5627a6a82595
Revises: 928e1d53a87b
Create Date: 2021-12-27 14:54:56.387189

"""
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
from sqlmodel import AutoString

from alembic import op
from iris.commons.models.base import JSONType, ListType

revision = "5627a6a82595"
down_revision = "928e1d53a87b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "measurement",
        sa.Column(
            "tool",
            sa.Enum("DiamondMiner", "Yarrp", "Ping", "Probes", name="tool"),
            nullable=True,
        ),
        sa.Column("tags", ListType(), nullable=True),
        sa.Column("user_id", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "Canceled",
                "Finished",
                "Ongoing",
                "Unknown",
                "Waiting",
                name="measurementstate",
            ),
            nullable=True,
        ),
        sa.Column("uuid", AutoString(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_measurement_end_time"), "measurement", ["end_time"], unique=False
    )
    op.create_index(
        op.f("ix_measurement_start_time"), "measurement", ["start_time"], unique=False
    )
    op.create_index(op.f("ix_measurement_uuid"), "measurement", ["uuid"], unique=False)
    op.create_table(
        "measurementagent",
        sa.Column("tool_parameters", JSONType(), nullable=True),
        sa.Column("agent_parameters", JSONType(), nullable=True),
        sa.Column("probing_statistics", JSONType(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "Canceled",
                "Finished",
                "Ongoing",
                "Unknown",
                "Waiting",
                name="measurementstate",
            ),
            nullable=True,
        ),
        sa.Column("probing_rate", sa.Integer(), nullable=True),
        sa.Column("target_file", AutoString(), nullable=False),
        sa.Column("measurement_uuid", AutoString(), nullable=True),
        sa.Column("agent_uuid", AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["measurement_uuid"],
            ["measurement.uuid"],
        ),
        sa.PrimaryKeyConstraint("measurement_uuid", "agent_uuid"),
    )
    op.create_index(
        op.f("ix_measurementagent_agent_uuid"),
        "measurementagent",
        ["agent_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_measurementagent_measurement_uuid"),
        "measurementagent",
        ["measurement_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_measurementagent_probing_rate"),
        "measurementagent",
        ["probing_rate"],
        unique=False,
    )
    op.create_index(
        op.f("ix_measurementagent_target_file"),
        "measurementagent",
        ["target_file"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_measurementagent_target_file"), table_name="measurementagent"
    )
    op.drop_index(
        op.f("ix_measurementagent_probing_rate"), table_name="measurementagent"
    )
    op.drop_index(
        op.f("ix_measurementagent_measurement_uuid"), table_name="measurementagent"
    )
    op.drop_index(op.f("ix_measurementagent_agent_uuid"), table_name="measurementagent")
    op.drop_table("measurementagent")
    op.drop_index(op.f("ix_measurement_uuid"), table_name="measurement")
    op.drop_index(op.f("ix_measurement_start_time"), table_name="measurement")
    op.drop_index(op.f("ix_measurement_end_time"), table_name="measurement")
    op.drop_table("measurement")
    # ### end Alembic commands ###
