"""add batch_size to MeasurementAgent

Revision ID: 8a9c14d43b43
Revises: 2f6d40d1b807
Create Date: 2022-05-25 10:13:35.407112

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8a9c14d43b43"
down_revision = "2f6d40d1b807"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "measurement_agent", sa.Column("batch_size", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("measurement_agent", "batch_size")
    # ### end Alembic commands ###
