"""make measurement.tool non-nullable

Revision ID: 9dc1b96c99eb
Revises: 5084010a40a4
Create Date: 2022-01-18 10:35:38.662786

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9dc1b96c99eb"
down_revision = "5084010a40a4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "measurement", "tool", existing_type=sa.VARCHAR(length=12), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "measurement", "tool", existing_type=sa.VARCHAR(length=12), nullable=True
    )
    # ### end Alembic commands ###
