"""upgrade fastapi-users

Revision ID: dfb29dfa2345
Revises: 081ad64ef916
Create Date: 2023-11-12 17:19:46.194608

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "dfb29dfa2345"
down_revision = "081ad64ef916"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "hashed_password",
        existing_type=sa.VARCHAR(length=72),
        type_=sa.String(length=1024),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "hashed_password",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=72),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
