FROM ubuntu:20.04
LABEL maintainer="Matthieu Gouel <matthieu.gouel@lip6.fr>"
ENV DEBIAN_FRONTEND=noninteractive

# TODO: Remove build-essential and python3-dev once
# we can push binary wheels on PyPI for diamond-miner.
RUN apt-get update \
    && apt-get install --no-install-recommends --yes \
        build-essential \
        ca-certificates \
        curl \
        mtr \
        python3-dev \
        python3-pip \
        zstd \
    && rm -rf /var/lib/apt/lists/*

RUN curl --location --output /usr/bin/clickhouse \
    https://builds.clickhouse.tech/master/$(arch | sed -e "s/x86_64/amd64/")/clickhouse && \
    chmod +x /usr/bin/clickhouse

WORKDIR /app

RUN mkdir targets
RUN mkdir results

RUN mkdir vendors
COPY vendors/diamond-miner vendors/diamond-miner

RUN pip3 install --no-cache-dir --upgrade pip \
    && pip install poetry uvicorn \
    && rm -rf /root/.cache/*

RUN poetry config virtualenvs.create false

COPY pyproject.toml pyproject.toml
COPY poetry.lock poetry.lock

RUN poetry install --no-dev --extras "agent api standalone worker" \
    && rm -rf /root/.cache/*

COPY iris iris
COPY statics/excluded_prefixes statics/excluded_prefixes
RUN mv iris/standalone/main.py main.py

ENTRYPOINT ["python3", "main.py"]
CMD ["--help"]
