FROM matthieugouel/diamond-miner-prober:0.1.7
LABEL key="Matthieu Gouel <matthieu.gouel@lip6.fr>"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN mkdir vendors
COPY vendors/diamond-miner-core vendors/diamond-miner-core

RUN pip3 install poetry \
    && rm -rf /root/.cache/*
RUN poetry config virtualenvs.create false

COPY pyproject.toml pyproject.toml
RUN poetry install --no-root --no-dev \
    && rm -rf /root/.cache/*

COPY iris iris
COPY iris/agent/main.py main.py

RUN mkdir targets
RUN mkdir results

COPY statics/excluded_prefixes statics/excluded_prefixes
COPY statics/index.html statics/index.html
# TODO: Expose another port to avoid conflict with traefik (on heartbeat)
EXPOSE 80

ENTRYPOINT []
CMD python3 -m http.server -d statics/ 80 & python3 -u main.py
