FROM tiangolo/uvicorn-gunicorn:python3.8
LABEL key="Matthieu Gouel <matthieu.gouel@lip6.fr>"

RUN apt-get update
RUN apt -y install --reinstall ca-certificates

WORKDIR /app

RUN mkdir vendors
COPY vendors/diamond-miner vendors/diamond-miner

RUN pip install --upgrade pip
RUN pip install poetry
RUN poetry config virtualenvs.create false

COPY pyproject.toml pyproject.toml
RUN poetry install --no-root --no-dev

COPY iris iris
