FROM tiangolo/uvicorn-gunicorn:python3.8
LABEL key="Matthieu Gouel <matthieu.gouel@gmail.com>"

WORKDIR /app

RUN pip install --upgrade pip
RUN pip install poetry
RUN poetry config virtualenvs.create false

COPY pyproject.toml pyproject.toml
RUN poetry install --no-root --no-dev

COPY iris iris
