FROM matthieugouel/diamond-miner-prober
LABEL key="Matthieu Gouel <matthieu.gouel@lip6.fr>"

RUN : \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        software-properties-common \
    && add-apt-repository -y ppa:deadsnakes \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        python3.9 \
        python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && :

# Web page
RUN : \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        nginx \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && :
RUN rm -f /var/www/html/*
COPY statics/index.html /var/www/html/index.html
EXPOSE 80

WORKDIR /app

RUN mkdir vendors
COPY vendors/diamond-miner-core vendors/diamond-miner-core

RUN pip3 install --upgrade pip
RUN pip3 install poetry
RUN poetry config virtualenvs.create false

COPY pyproject.toml pyproject.toml
RUN poetry install --no-root --no-dev

COPY iris iris
COPY iris/agent/main.py main.py

RUN mkdir targets
RUN mkdir results

ENTRYPOINT []
CMD nginx ; python3.9 -u main.py