FROM ubuntu:20.04
LABEL key="Matthieu Gouel <matthieu.gouel@lip6.fr>"

ENV DEBIAN_FRONTEND=noninteractive

# TODO: Remove build-essential and python3-dev once
# we can push binary wheels on PyPI for diamond-miner.
RUN apt-get update \
    && apt-get install -y -q --no-install-recommends \
        apt-transport-https \
        ca-certificates \
        dirmngr \
        gnupg2 \
        python3-pip \
        build-essential \
        python3-dev \
        zstd \
        mtr \
    && rm -rf /var/lib/apt/lists/*

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E0C56BD4 \
    && echo "deb https://repo.clickhouse.tech/deb/stable/ main/" > \
        /etc/apt/sources.list.d/clickhouse.list \
    && apt-get update \
    && apt-get install -y -q --no-install-recommends \
        clickhouse-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN mkdir targets
RUN mkdir results

RUN mkdir vendors
COPY vendors/diamond-miner vendors/diamond-miner

RUN pip3 install --no-cache-dir --upgrade pip \
    && pip install poetry uvicorn \
    && rm -rf /root/.cache/*

RUN poetry config virtualenvs.create false

COPY pyproject.toml pyproject.toml
COPY poetry.lock poetry.lock

RUN poetry install --no-dev \
    && rm -rf /root/.cache/*

COPY iris iris
COPY statics/excluded_prefixes statics/excluded_prefixes
RUN mv iris/standalone/main.py main.py

ENTRYPOINT ["python3", "main.py"]
CMD ["--help"]
