from typing import Generic, Iterator, TypeVar

K = TypeVar("K")
V = TypeVar("V")

class PyTricia(Generic[K, V]):
    def __init__(self, prefixlen: int): ...
    def __iter__(self) -> Iterator[K]: ...
    def __getitem__(self, prefix: K) -> V: ...
    def __setitem__(self, prefix: K, value: V): ...
    def get(self, prefix: K) -> V: ...
