name: Publish Iris Agent 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish Iris Agent to Docker Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: matthieugouel/iris-agent
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./dockerfiles/Dockerfile-agent
