name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: dioptra-io/setup-poetry-action@v1
      - name: Start services
        run: docker compose up -d -t 0 traefik clickhouse minio postgres redis
      - name: Install package
        run: poetry install
      - name: Run tests
        run: sudo env CI=1 $(poetry env info -p)/bin/pytest --cov=iris --cov-report=xml --log-cli-level=INFO
      - uses: codecov/codecov-action@v2

  docker:
    needs: [test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - iris-agent
          - iris-api
          - iris-worker
    steps:
      - uses: actions/checkout@v3
      - uses: dioptra-io/publish-docker-action@v1.4
        with:
          file: ./dockerfiles/${{ matrix.image }}.dockerfile
          image: dioptra-io/iris/${{ matrix.image }}
          password: ${{ secrets.GITHUB_TOKEN }}
          # platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' }}
